name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-base:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd base-img && docker build . --file Dockerfile --tag docker.io/tylerwarre/fuzz-base:$(date +%s)
